#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <assert.h>
#include <netinet/in.h>
#include <netdb.h>
#include <fcntl.h>

#include <linux/bpf.h>
#include <linux/filter.h>
#include "../bpf_load.h"
//#include <bpf/libbpf.h>
#ifndef __NR_bpf
# if defined(__i386__)
#  define __NR_bpf 357
# elif defined(__x86_64__)
#  define __NR_bpf 321
# elif defined(__aarch64__)
#  define __NR_bpf 280
# elif defined(__sparc__)
#  define __NR_bpf 349
# elif defined(__s390__)
#  define __NR_bpf 351
# elif defined(__arc__)
#  define __NR_bpf 280
# else
#  error __NR_bpf not defined. libbpf does not support your arch.
# endif
#endif

static inline int sys_bpf(enum bpf_cmd cmd, union bpf_attr *attr,
                          unsigned int size)
{
    return syscall(__NR_bpf, cmd, attr, size);
}

#define LOG_BUF_SIZE 16384

int
bpf_prog_load(enum bpf_prog_type type,
              const struct bpf_insn *insns, int insn_cnt,
              const char *license) {
    char bpf_log_buf[LOG_BUF_SIZE] = {0};

    union bpf_attr attr;
    attr.prog_type = type;
    attr.insns     = (uint64_t)(insns);
    attr.insn_cnt  = insn_cnt;
    attr.license   = (uint64_t)(license);
    attr.log_buf   = (uint64_t)(bpf_log_buf);
    attr.log_size  = LOG_BUF_SIZE;
    attr.log_level = 1;
    
    int ret = sys_bpf(BPF_PROG_LOAD, &attr, sizeof(attr));
    if (ret < 0) {
        fprintf(stderr, "%s\n", bpf_log_buf);
    }
    union bpf_attr map_attr;
    map_attr.map_type = BPF_MAP_TYPE_HASH;
    map_attr.key_size = sizeof(uint64_t);
    map_attr.value_size = sizeof(uint64_t);
    map_attr.max_entries = 8;
    map_attr.map_flags = 0;
    int map = sys_bpf(BPF_MAP_CREATE, &map_attr, sizeof(map_attr));
    if (map < 0) {
        perror("MAP CREATION");
        return map;
    }
    return ret;
}

int xbpf_map_update_elem(int fd, const void *key, const void *value,	__u64 flags) {
    union bpf_attr attr;
    attr.map_fd = fd;
    attr.flags = flags;
    attr.map_fd = fd;
    attr.key = key;
    attr.value = value;
    return sys_bpf(BPF_MAP_UPDATE_ELEM, &attr, sizeof(attr));
}
    
int load_elf_bpf(int sockfd, const char*filename) {
    int i;
    /*
    static int local_fixup_map_fd = 0;
    void local_fixup_map_cb(struct bpf_map_data *map, int idx) {
        printf("CALLBACK FROM KERNEL WITH %d %d\n", idx, map->fd);
        local_fixup_map_fd = map->fd;
        }*/
    int ret = load_bpf_file(filename);
    if (ret != 0) {
        perror("ERror loading ELF");
        return ret;
    }
    fprintf(stderr, "LOADING FROM %d fd's\n", prog_cnt);
    for (i=0;i<prog_cnt;++i) {
        fprintf(stderr, "LOADING FROM %d fd: %d\n", i, prog_fd[i]);
        if (setsockopt(sockfd, SOL_SOCKET, SO_ATTACH_BPF, &prog_fd[i], sizeof(prog_fd[i]))) {
            perror("setsockopt ATTACH_FILTER");
            return -1;
        }
    }
    return map_data_count?map_fd[0]:-1;
}

int load_bpf_by_file(int sockfd, const char*filename) {
    
    FILE * fp = fopen(filename, "rb");
    if (!fp) {
        return -1;
    }
    uint8_t * bpf_program = NULL;
    uint8_t tmp[1024];
    size_t bpf_program_len = 0;
    while(1) {
        size_t count = fread(tmp, 1, sizeof(tmp), fp);
        if (count ==0) {
            break;
        }
        bpf_program_len += count;
        bpf_program = realloc(bpf_program, bpf_program_len);
        memcpy(bpf_program + bpf_program_len - count, tmp, count);
    }
    fclose(fp);
    int bpf_fd = bpf_prog_load(BPF_PROG_TYPE_SOCKET_FILTER, (const struct bpf_insn *)bpf_program, bpf_program_len/ sizeof(struct bpf_insn), "BSD");
    if (bpf_fd < 0) {
        return bpf_fd;
    }
    /*
    struct sock_filter *bpf_bytecode = (sock_filter*)bpf_program.data(); // bytecode generated by hand or using "tcpdump -dd"
    struct sock_fprog fprog = { (uint16_t)(bpf_program.size() / sizeof(bpf_insn)), bpf_bytecode};
    */
    if (setsockopt(sockfd, SOL_SOCKET, SO_ATTACH_BPF, &bpf_fd, sizeof(bpf_fd))) {
		perror("setsockopt ATTACH_FILTER");
		return 1;
	}
    return 0;
}


int send_packets(int src_port, int dst_port, int count) {
    int sockfd;
    int i;
    struct sockaddr_in srvaddr, cliaddr;
    uint8_t data[8] = {'0','b','a','d', 'f','0', '0','0'};
    memset(&cliaddr, 0, sizeof(cliaddr));
      
    // Filling client information
    cliaddr.sin_family    = AF_INET; // IPv4
    cliaddr.sin_addr.s_addr = INADDR_ANY;
    cliaddr.sin_port = htons(src_port);
    
    srvaddr.sin_family    = AF_INET; // IPv4
    srvaddr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    srvaddr.sin_port = htons(dst_port);
    if ( (sockfd = socket(AF_INET, SOCK_DGRAM, 0)) < 0 ) {
        perror("socket creation failed");
        exit(EXIT_FAILURE);
    }
    if ( bind(sockfd, (const struct sockaddr *)&cliaddr, 
            sizeof(cliaddr)) < 0 )
    {
        perror("bind failed");
        exit(EXIT_FAILURE);
    }
    for (i = 0;i <count ; ++i) {
        data[7] = 'a' + i% 10;
        data[6] = '0' + (i/ 10)% 10;
        data[5] = '0' + (i/ 100)% 10;
        int ret = sendto(sockfd, data, sizeof(data),
                         0, (const struct sockaddr *) &srvaddr, 
                         sizeof(srvaddr));
        //fprintf(stderr, "%d->%d %d\n", src_port,  dst_port, ret);
        assert(ret == sizeof(data));
    }
    close(sockfd);
}
#define MAXLINE 65537
int main(int argc, char**argv) {
    int i;
    int sockfd;
    char buffer[MAXLINE] = {0};
    struct sockaddr_in srvaddr, cliaddr;
      
    // Creating socket file descriptor
    if ( (sockfd = socket(AF_INET, SOCK_DGRAM, 0)) < 0 ) {
        perror("socket creation failed");
        exit(EXIT_FAILURE);
    }
    
    int flags = fcntl(sockfd, F_GETFL, 0);
    if (flags == -1) return false;
    if (fcntl(sockfd, F_SETFL, flags | O_NONBLOCK) < 0) {
        perror("NONBLOCK");
    }
/*
    if (load_bpf_by_file(sockfd, "limited_per_source.bpf") < 0) {
        perror("BPF FAILED");
    }
*/
    int buffer_reset_fd = load_elf_bpf(sockfd, "limited_per_source.o");
    if (buffer_reset_fd < 0) {
        perror("BPF FAILED");
    }
    long zero = 0;
    long framecycles = 0;
    bpf_map_update_elem(buffer_reset_fd, &zero, &framecycles, 0);
    memset(&srvaddr, 0, sizeof(srvaddr));
    memset(&cliaddr, 0, sizeof(cliaddr));
      
    // Filling server information
    srvaddr.sin_family    = AF_INET; // IPv4
    srvaddr.sin_addr.s_addr = INADDR_ANY;
    srvaddr.sin_port = 0;
      
    // Bind the socket with the server address
    if ( bind(sockfd, (const struct sockaddr *)&srvaddr, 
            sizeof(srvaddr)) < 0 )
    {
        perror("bind failed");
        exit(EXIT_FAILURE);
    }
    socklen_t srvlen = sizeof(srvaddr);
    getsockname(sockfd, (struct sockaddr*)&srvaddr, &srvlen);
    uint16_t port = ntohs(srvaddr.sin_port);
    for (framecycles= 0;framecycles<8;++framecycles) {
        bpf_map_update_elem(buffer_reset_fd, &zero, &framecycles, 0);        
        send_packets(9999, port, 16);
        send_packets(9998, port, 16);
        socklen_t len, n;
        
        for (i = 0; i <  32; ++ i) {
            len = sizeof(cliaddr);  //len is value/resuslt
            n = recvfrom(sockfd, (char *)buffer, MAXLINE - 1, 
                         MSG_WAITALL, ( struct sockaddr *) &cliaddr,
                         &len);
            if (n == -1) {
                printf("NO MORE DATA\n");
                break;
            }
            buffer[n] = '\0';
            char addr_buffer[INET6_ADDRSTRLEN];
            if (getnameinfo((struct sockaddr*)&cliaddr,len,addr_buffer,sizeof(addr_buffer),
                            0,0,0) < 0) {
                perror("getname info error");
            }
            printf("[%s:%d]: %s\n",addr_buffer, ntohs(cliaddr.sin_port), buffer);
            fflush(stdout);
        }/*
        long xdata = -1;
        int ret = bpf_map_lookup_elem(buffer_reset_fd, &zero, &xdata);
        if (ret < 0) {
            perror("LOOKUP OF SET ELEMENT");
        }
        fprintf(stderr, "WHAT IS THIS %ld\n",xdata);
         */
    }
    return 0;
}

